### PR TITLE
init de_dev-0.0.0

### PR DESCRIPTION
**Pull request by tuuzdu**
###### Motivation for this change
Development requires for Drone Employee

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by akru** [comment]
Could you move sources to separate repository and fetch it from github? Please do not commit sources to airapkgs, only nix and patches. It helps you to develop sources idependently to airapkgs. Finally changes in airapkgs will be more predictable and simple.

**Comment by tuuzdu** [comment]
Yes, I have thought about it, but sources so small. I will create repository for sources and send pull request again.

**Comment by akru** [comment]
You can just resend commit to this PR.

**Comment by tuuzdu** [comment]
Done!

**Comment by akru** [comment]
Could you [squash](https://git-scm.com/book/ru/v1/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%9F%D0%B5%D1%80%D0%B5%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D1%8C-%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D0%B8) commits of this PR?

**Pull request merged**
